### ISSUE TITLE
[feature] make program more secure in dns resolv.conf

### ISSUE THREAD

**Issue by Paper-Dragon** [blechschmidt/tun2proxy#68]
Hi all:

如下代码，使用  `CAP_SYS_ADMIN`  ，在docker内必须使用  `--privileged` 选项进行提权才能使用。这是一个不安全因素，完全可以修改 /etc/resolv.conf 文件而不是bind mount。这样会使用更高的权限。

https://github.com/blechschmidt/tun2proxy/blob/61690145646848e1212f8579c718b91e2b66aed2/src/setup.rs#L174-L180

因为我并不是很懂rust语言，如果用shell实现，应该如下这样。
这样就不会使用过高的权限造成安全问题。

```shell
sudo sh -c "echo nameserver 8.8.8.8 > /etc/resolv.conf"
```
我本想写一个pull request来解决这个问题，因为对rust不够熟悉，心有余而力不足。

若这个问题被解决，我将会提交docker support优化后的的部分脚本。

下面是一些可能有用的日志
```
root@aaec7b8244ec:/# RUST_BACKTRACE=full tun2proxy --proxy socks5://gPkSOKMlJe:YuYMma2c0C@54.179.216.21:56471  --dns over-tcp --tun tun0  --setup auto
[2023-10-08T05:21:00Z INFO  tun2proxy] Proxy socks5 server: 54.179.216.21:56471
[DEBUG shoulong] -> try function configure <-
[2023-10-08T05:21:00Z INFO  tun2proxy::setup] [240] Setting up network configuration
[DEBUG shoulong] -> verify you r root <-
[DEBUG shoulong] -> try tunnel bypass addr  <-
[DEBUG shoulong] -> end tunnel bypass addr  <-
[DEBUG shoulong] -> try fork child  <-
[DEBUG shoulong] -> fork into child  <-
[DEBUG shoulong] -> into setup_and_handle_signals  <-
[DEBUG shoulong] -> try add tuntap device  <-
[DEBUG shoulong] -> end add tuntap device  <-
[DEBUG shoulong] -> try add ip route <-
[DEBUG shoulong] -> end add ip route <-
[DEBUG shoulong] -> try into route_proxy_address <-
[DEBUG shoulong] -> into route_proxy_address <-
[DEBUG shoulong] -> try read route table <-
[DEBUG shoulong] -> end read route table <-
[DEBUG shoulong] -> end try into route_proxy_address <-
[DEBUG shoulong] -> delete_proxy_route is true <-
[DEBUG shoulong] -> try into setup_resolv_conf <-
[DEBUG shoulong] -> into setup_resolv_conf <-
[DEBUG shoulong] -> in setup_resolv_conf source /proc/self/fd/3 <-
[DEBUG shoulong] -> in setup_resolv_conf before mount
[2023-10-08T05:21:00Z ERROR tun2proxy::setup] nix::errno::Errno EPERM
[2023-10-08T05:21:00Z INFO  tun2proxy::setup] [241] Restoring network configuration
thread 'main' panicked at src/setup.rs:295:29:
called `Result::unwrap()` on an `Err` value: OSError(EPERM)
stack backtrace:
...
 17:     0x55ce2ae8b558 - tun2proxy::setup::Setup::setup_and_handle_signals::h3f256d76aae9dea6
  18:     0x55ce2ae8fd47 - tun2proxy::setup::Setup::configure::hd5cf214a9dd68097
  19:     0x55ce2ad9e9e2 - tun2proxy::main::hb4d0a62c8808e9df
  20:     0x55ce2ada6d43 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7c7c3321b3fbb7e5
  21:     0x55ce2adab319 - std::rt::lang_start::{{closure}}::h6b912e9e34076fdc
  22:     0x55ce2afa76eb - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hbcc4f8a3f5ada78c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:284:13
  23:     0x55ce2afa76eb - std::panicking::try::do_call::he5f117a9e13dadde
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  24:     0x55ce2afa76eb - std::panicking::try::h2f3af9afce3a0443
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  25:     0x55ce2afa76eb - std::panic::catch_unwind::h6d6c387f38ef05ea
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  26:     0x55ce2afa76eb - std::rt::lang_start_internal::{{closure}}::h6ca09d5905711415
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:48
  27:     0x55ce2afa76eb - std::panicking::try::do_call::ha9fd18ea06654a4b
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  28:     0x55ce2afa76eb - std::panicking::try::hda5c2a4432362341
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  29:     0x55ce2afa76eb - std::panic::catch_unwind::h440f731b142bc235
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  30:     0x55ce2afa76eb - std::rt::lang_start_internal::hc0b4e50f058f62ce
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:20
  31:     0x55ce2ada36e5 - main
  32:     0x7fc0638121ca - <unknown>
  33:     0x7fc063812285 - __libc_start_main
  34:     0x55ce2ad93361 - _start
  35:                0x0 - <unknown>
[2023-10-08T05:21:00Z ERROR tun2proxy] Failed to read from pipe
root@aaec7b8244ec:/# mount --bind /tmp/tun2proxy-resolv.conf  /etc/resolv.conf
mount: /etc/resolv.conf: mount point is not a directory.
       dmesg(1) may have more information after failed mount system call.



```
Thanks,
Paper-Dragon

**Comment by ssrlive** [comment]
你改寫腳本吧。改法參考  https://github.com/blechschmidt/tun2proxy/issues/18#issuecomment-1488002129

**Comment by blechschmidt** [comment]
Root does not appear to have mount permissions inside a Docker container if it is not run in privileged mode. cea0e0fa271d669d1af0770f6d8482bc7ea03814 should fix this by writing to `/etc/resolv.conf` directly in case mounting fails. I'm going to leave this issue open since in the second case `/etc/resolv.conf` still needs to be restored upon closing tun2proxy.

**Comment by blechschmidt** [comment]
Closing this with 299b51667d719f960772b3435096ff336b91c733.
