### ISSUE TITLE
tun2proxy getting stuck in iperf tests

### ISSUE THREAD

**Issue by blechschmidt** [blechschmidt/tun2proxy#79]
Currently, tun2proxy does not transmit any data during the reverse iperf (download) test. Further, the first (upload) test is very slow (110 Kbits/sec). Output as follows:
```
+++ dirname ./myscript.sh
++ cd .
++ pwd
+ SCRIPT_DIR=/home/vagrant/tun2proxy/tests/iperf
+ echo /home/vagrant/tun2proxy/tests/iperf
/home/vagrant/tun2proxy/tests/iperf
+ netns=test
+ dante=sockd
+ iperf=iperf
+ tun2proxy=/home/vagrant/tun2proxy/tests/iperf/../../target/release/tun2proxy
+ sudo systemctl stop danted
Failed to stop danted.service: Unit danted.service not loaded.
+ sleep 1
+ ip netns add test
+ ip link add veth0 type veth peer name veth0 netns test
+ ip addr add 10.0.0.2/24 dev veth0
+ ip link set dev veth0 up
+ ip netns exec test ip addr add 10.0.0.3/24 dev veth0
+ ip netns exec test ip addr add 10.0.0.4/24 dev veth0
+ ip netns exec test ip link set dev veth0 up
+ ip netns exec test ip addr add 127.0.0.1/8 dev lo
+ ip netns exec test ip link set dev lo up
+ echo 'Starting Dante in background ...'
Starting Dante in background ...
+ ip netns exec test sockd -f /home/vagrant/tun2proxy/tests/iperf/dante.conf
+ sleep 1
+ ip netns exec test iperf -s -B 10.0.0.4
------------------------------------------------------------
Server listening on TCP port 5001
TCP window size:  128 KByte (default)
------------------------------------------------------------
+ ip tuntap add name tun0 mode tun
+ ip link set tun0 up
+ ip route add 10.0.0.4 dev tun0
+ iperf -c 10.0.0.4
+ /home/vagrant/tun2proxy/tests/iperf/../../target/release/tun2proxy --proxy socks5://10.0.0.3:1080
[2023-11-18T13:19:27Z INFO  tun2proxy] Proxy socks5 server: 10.0.0.3:1080
------------------------------------------------------------
Client connecting to 10.0.0.4, TCP port 5001
[2023-11-18T13:19:27Z INFO  tun2proxy::tun2proxy] TCP 10.0.2.15:58524 -> 10.0.0.4:5001 (10.0.0.4:5001)
[2023-11-18T13:19:27Z INFO  tun2proxy::tun2proxy] Close TCP 10.0.2.15:58524 -> 10.0.0.4:5001
TCP window size: 85.0 KByte (default)
------------------------------------------------------------
[  1] local 10.0.2.15 port 58524 connected with 10.0.0.4 port 5001 (icwnd/mss/irtt=14/1460/407)
[2023-11-18T13:19:27Z INFO  tun2proxy::tun2proxy] UDP associate session UDP [fe80::ee03:e557:41fa:43fb]:5355 -> [ff02::1:3]:5355 ([ff02::1:3]:5355)
[2023-11-18T13:19:27Z INFO  tun2proxy::tun2proxy] UDP associate session UDP [fe80::ee03:e557:41fa:43fb]:5353 -> [ff02::fb]:5353 ([ff02::fb]:5353)
[2023-11-18T13:19:27Z INFO  tun2proxy::tun2proxy] Close UDP [fe80::ee03:e557:41fa:43fb]:5353 -> [ff02::fb]:5353
[2023-11-18T13:19:27Z INFO  tun2proxy::tun2proxy] Close UDP [fe80::ee03:e557:41fa:43fb]:5355 -> [ff02::1:3]:5355
[2023-11-18T13:19:27Z INFO  tun2proxy::tun2proxy] UDP associate session UDP [fe80::ee03:e557:41fa:43fb]:5353 -> [ff02::fb]:5353 ([ff02::fb]:5353)
[2023-11-18T13:19:27Z INFO  tun2proxy::tun2proxy] UDP associate session UDP [fe80::ee03:e557:41fa:43fb]:5355 -> [ff02::1:3]:5355 ([ff02::1:3]:5355)
[2023-11-18T13:19:27Z INFO  tun2proxy::tun2proxy] Close UDP [fe80::ee03:e557:41fa:43fb]:5353 -> [ff02::fb]:5353
[2023-11-18T13:19:27Z INFO  tun2proxy::tun2proxy] Close UDP [fe80::ee03:e557:41fa:43fb]:5355 -> [ff02::1:3]:5355
[2023-11-18T13:19:28Z INFO  tun2proxy::tun2proxy] UDP associate session UDP [fe80::ee03:e557:41fa:43fb]:5355 -> [ff02::1:3]:5355 ([ff02::1:3]:5355)
[2023-11-18T13:19:28Z INFO  tun2proxy::tun2proxy] Close UDP [fe80::ee03:e557:41fa:43fb]:5355 -> [ff02::1:3]:5355
[2023-11-18T13:19:28Z INFO  tun2proxy::tun2proxy] UDP associate session UDP [fe80::ee03:e557:41fa:43fb]:5353 -> [ff02::fb]:5353 ([ff02::fb]:5353)
[2023-11-18T13:19:28Z INFO  tun2proxy::tun2proxy] Close UDP [fe80::ee03:e557:41fa:43fb]:5353 -> [ff02::fb]:5353
[2023-11-18T13:19:28Z INFO  tun2proxy::tun2proxy] UDP associate session UDP [fe80::ee03:e557:41fa:43fb]:5353 -> [ff02::fb]:5353 ([ff02::fb]:5353)
[2023-11-18T13:19:28Z INFO  tun2proxy::tun2proxy] Close UDP [fe80::ee03:e557:41fa:43fb]:5353 -> [ff02::fb]:5353
[2023-11-18T13:19:29Z INFO  tun2proxy::tun2proxy] UDP associate session UDP [fe80::ee03:e557:41fa:43fb]:5353 -> [ff02::fb]:5353 ([ff02::fb]:5353)
[2023-11-18T13:19:29Z INFO  tun2proxy::tun2proxy] Close UDP [fe80::ee03:e557:41fa:43fb]:5353 -> [ff02::fb]:5353
[ ID] Interval       Transfer     Bandwidth
[  1] 0.0000-10.3447 sec   138 KBytes   110 Kbits/sec
+ sleep 3
+ iperf -c 10.0.0.4 -R
------------------------------------------------------------
Client connecting to 10.0.0.4, TCP port 5001
TCP window size: 16.0 KByte (default)
------------------------------------------------------------
[2023-11-18T13:19:40Z INFO  tun2proxy::tun2proxy] TCP 10.0.2.15:44816 -> 10.0.0.4:5001 (10.0.0.4:5001)
[2023-11-18T13:19:40Z INFO  tun2proxy::tun2proxy] Close TCP 10.0.2.15:44816 -> 10.0.0.4:5001
[  1] local 10.0.2.15 port 44816 connected with 10.0.0.4 port 5001 (reverse) (icwnd/mss/irtt=14/1460/278)
[ ID] Interval       Transfer     Bandwidth
[ *1] 0.0000-0.0000 sec  0.000 Bytes  0.000 bits/sec
+ sleep 10
```

To reproduce using vagrant:
```
vagrant init archlinux/archlinux
vagrant up
vargant ssh
```

Test script:
```
#!/bin/bash

# sudo apt install iperf3 dante-server
set -x

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo $SCRIPT_DIR

netns="test"
dante="sockd"
iperf="iperf"
tun2proxy="${SCRIPT_DIR}/../../target/release/tun2proxy"

sudo systemctl stop danted
sleep 1

ip netns add "$netns"

ip link add veth0 type veth peer name veth0 netns "$netns"

# Configure veth0 in default ns
ip addr add 10.0.0.2/24 dev veth0
ip link set dev veth0 up

# Configure veth0 in child ns
ip netns exec "$netns" ip addr add 10.0.0.3/24 dev veth0
ip netns exec "$netns" ip addr add 10.0.0.4/24 dev veth0
ip netns exec "$netns" ip link set dev veth0 up

# Configure lo interface in child ns
ip netns exec "$netns" ip addr add 127.0.0.1/8 dev lo
ip netns exec "$netns" ip link set dev lo up

echo "Starting Dante in background ..."
ip netns exec "$netns" "$dante" -f ${SCRIPT_DIR}/dante.conf &

# Start iperf3 server in netns
ip netns exec "$netns" "$iperf" -s -B 10.0.0.4 &

sleep 1

# Prepare tun2proxy
ip tuntap add name tun0 mode tun
ip link set tun0 up
ip route add 10.0.0.4 dev tun0
"$tun2proxy" --proxy socks5://10.0.0.3:1080 &

"$iperf" -c 10.0.0.4
sleep 3

"$iperf" -c 10.0.0.4 -R

sleep 10
```

Packages for building and testing can be installed as follows (as root):
```
pacman -Syuu
pacman -S rust git dante iperf
```

@ssrlive, can you reproduce this?

**Comment by ssrlive** [comment]
can not start vagrant, log:
```
root@pc:~# vagrant up
Bringing machine 'default' up with 'libvirt' provider...
#<Thread:0x000055d0bc4b6bc0@/usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/batch_action.rb:71 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	25: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
	24: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:188:in `action'
	23: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:188:in `call'
	22: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/environment.rb:592:in `lock'
	21: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:202:in `block in action'
	20: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:227:in `action_raw'
	19: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
	18: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
	17: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
	16: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
	15: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	14: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	13: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	12: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/box_check_outdated.rb:31:in `call'
	11: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	10: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/call.rb:52:in `call'
	 9: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:170:in `to_app'
	 8: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:170:in `new'
	 7: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:20:in `initialize'
	 6: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:20:in `map'
	 5: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:20:in `block in initialize'
	 4: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:90:in `finalize_action'
	 3: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:90:in `new'
	 2: from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.43/lib/vagrant-libvirt/action/create_networks.rb:26:in `initialize'
	 1: from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.43/lib/vagrant-libvirt/driver.rb:40:in `connection'
/usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.43/lib/vagrant-libvirt/driver.rb:43:in `rescue in connection': Error while connecting to libvirt: Error making a connection to libvirt URI qemu:///system?no_verify=1&keyfile=/root/.ssh/id_rsa: (VagrantPlugins::ProviderLibvirt::Errors::FogLibvirtConnectionError)
Call to virConnectOpen failed: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory
Error while connecting to libvirt: Error making a connection to libvirt URI qemu:///system?no_verify=1&keyfile=/root/.ssh/id_rsa:
Call to virConnectOpen failed: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory
```

**Comment by blechschmidt** [comment]
Does it maybe help to use the VirtualBox provider as described [here](https://superuser.com/questions/614941/vagrant-fails-to-create-box-with-libvirt)?
